set(CPACK_PACKAGE_NAME "AwaKurageDownloader")
set(CPACK_PACKAGE_VENDOR "AwaKurage")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${PROJECT_DESCRIPTION}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "AwaKurageDownloader")

if(WIN32)
    set(CMAKE_INSTALL_SYSTEM_RUNTIME_DESTINATION bin)
    include(InstallRequiredSystemLibraries)
endif()

if(WIN32)
    find_program(AWA_WIX_CANDLE candle.exe)
    find_program(AWA_WIX_LIGHT light.exe)

    if(AWA_WIX_CANDLE AND AWA_WIX_LIGHT)
        set(CPACK_GENERATOR "WIX")
        set(CPACK_WIX_UPGRADE_GUID "7F8DB8F5-2C9F-4F01-9C6D-3BBF7A7B8B74")
        if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/resources/icons/app.ico")
            set(CPACK_WIX_PRODUCT_ICON "${CMAKE_CURRENT_SOURCE_DIR}/resources/icons/app.ico")
        endif()
        set(CPACK_WIX_PROPERTY_ARPHELPLINK "https://example.invalid/awakurage")
        set(CPACK_PACKAGE_FILE_NAME "AwaKurageDownloader-${PROJECT_VERSION}-win64")
    else()
        message(WARNING "WiX candle/light were not found. CPack will generate a portable ZIP instead of an MSI.")
        set(CPACK_GENERATOR "ZIP")
        set(CPACK_PACKAGE_FILE_NAME "AwaKurageDownloader-${PROJECT_VERSION}-win64-portable")
    endif()
endif()

include(CPack)
